force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{MM}{DD}{YY}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PubSub</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <description>Order Types</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Order</fullName>
            </value>
            <value>
                <fullName>B2B Order</fullName>
            </value>
            <value>
                <fullName>Return Order</fullName>
            </value>
            <value>
                <fullName>B2C Order</fullName>
            </value>
            <value>
                <fullName>Standard Order</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <description>payment in months or percentage</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Net 10</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Net 20</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>Net 45</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>Net 75</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>order payment types</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Bank Financed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DF2023App_Test.cls
/**
 * @description       : Test class
 * @author            : Ramanathan
 * @group             : 
 * @last modified on  : 09-28-2023
 * @last modified by  : Ramanathan
**/

@isTest
private class DF2023App_Test {
    @testSetup static void setup() {
        Account tempAcc = new Account (Name = 'Test Account 1');
        insert tempAcc;

        Order__c ord1 = new Order__c(Account__c = tempAcc.Id, Channel__c = 'Queue', OrderType__c = 'Sales Order', PaymentTerms__c='10', PaymentType__c = 'Cash', Status__c='Pending');
        Order__c ord2 = new Order__c(Account__c = tempAcc.Id, Channel__c = 'PubSub', OrderType__c = 'Sales Order', PaymentTerms__c='10', PaymentType__c = 'Cash', Status__c='Pending');
        insert new List<Order__c> {ord1, ord2};
    }


    @isTest static void testDynamoDBCallout() {
        Order__c[] orders = [Select Id, Name, Channel__c From Order__c Limit 10];
        System.assert(orders.size() > 0);
        Test.setMock(HttpCalloutMock.class, new DynamoDBMock());
        DynamoPutRequest putreq = new DynamoPutRequest();
        putreq.externalId = orders[0].id;
        putreq.id=orders[0].id;
        putreq.name = orders[0].Name;
        putreq.orderdata = 'sample text json';
        putreq.requestId = orders[0].id;
        putreq.status = 'Pending';
        DynamoPutRequest[] putReqs = new List<DynamoPutRequest> {putreq};
        Test.startTest();
        List<DynamoPutResp> putRes = DynamoService.putItemRequest(putReqs);
        Test.stopTest();
        System.assert(putReqs != null);

    }
}